#!/usr/bin/env python3
"""Bake the Matter pairing QR into a C header.

    python3 tools/mkqr_header.py > include/arena_qr.h

The payload is fixed by the firmware: CONFIG_ENABLE_TEST_SETUP_PARAMS pins the
passcode to 20202021 and the discriminator to 3840, so the code never changes at
runtime and there is no reason to carry a QR encoder on the board. Re-run this
if the setup parameters ever move — and regenerate the printed card with it.

Verified 2026-08-03 against the running firmware: the board advertises
vendorID=65521 productID=32768 discriminator=3840/15, which is exactly what this
payload decodes to.
"""
import sys
try:
    import qrcode
except ImportError:
    sys.exit("pip install qrcode  (python3 -m venv .venv && .venv/bin/pip install qrcode)")

PAYLOAD = "MT:Y.K9042C00KA0648G00"     # passcode 20202021, discriminator 3840, VID FFF1, PID 8000
MANUAL  = "3497-011-2332"
QUIET   = 4                            # modules; without it phones will not lock on

q = qrcode.QRCode(version=None, error_correction=qrcode.constants.ERROR_CORRECT_L,
                  box_size=1, border=QUIET)
q.add_data(PAYLOAD)
q.make(fit=True)
m = q.get_matrix()
n = len(m)                             # side including the quiet zone

stride = (n + 7) // 8
out = []
for row in m:
    bits = bytearray(stride)
    for x, dark in enumerate(row):
        if dark:                       # 1 = dark module = lit pixel on an OLED
            bits[x >> 3] |= 0x80 >> (x & 7)
    out.append(bits)

w = sys.stdout.write
w("// Generated by tools/mkqr_header.py - do not edit by hand.\n")
w("// Matter pairing QR, quiet zone included. 1 bit per module, MSB first,\n")
w("// %d bytes per row. Dark module = lit pixel.\n" % stride)
w("#pragma once\n\n")
w('#define ARENA_QR_PAYLOAD  "%s"\n' % PAYLOAD)
w('#define ARENA_QR_MANUAL   "%s"\n' % MANUAL)
w("#define ARENA_QR_SIDE     %d          // modules, quiet zone included\n" % n)
w("#define ARENA_QR_STRIDE   %d\n\n" % stride)
w("static const uint8_t ARENA_QR[ARENA_QR_SIDE][ARENA_QR_STRIDE] = {\n")
for r in out:
    w("  { " + ", ".join("0x%02X" % b for b in r) + " },\n")
w("};\n")
